### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by ghost** [Ghosts/Maus#1]
Can you add a release please? because i don't know how to build it

**Comment by Ghosts** [comment]
Working on an issue with the client jar builder.

Once that works I'll upload an alpha release (1.5a) with the ability to create your own client jars for testing / connections!

Stay tuned.

**Comment by ghost** [comment]
Okay :)

**Comment by Ghosts** [comment]
https://github.com/Ghosts/Maus/releases/tag/1.0b

**Comment by Ghosts** [comment]
https://github.com/Ghosts/Maus/releases/tag/2.0b
