### ISSUE TITLE
Maus 2.0b and working in background

### ISSUE THREAD

**Issue by ghost** [Ghosts/Maus#4]
In the Maus 2.0b title is Maus 1.0b.
Also when you close Maus, it's still working in background so i need to force to end throug Taskbar(Win 10 x64Bit French Ultimate)

**Comment by Ghosts** [comment]
Under settings is "Background Persistence" enabled? If so Maus will stay open in the task bar (as an icon in the tray). I know I fixed a few bugs after the 2.0 release in regards to loading / saving settings but I'll investigate this further. 

What system are you running on?

**Comment by ghost** [comment]
So yup Maus run in background with notification tray.
Running Win 10 x64Bit French Ultimate (Fresh Version)
